#!/usr/bin/env python3

import sys
import os
import nltk
from nltk.tokenize import TweetTokenizer
from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    if len(sys.argv) != 2:
        print('./tweets @name')
        sys.exit(1)
    
    tweets = get_user_timeline(screen_name=sys.argv[1], count=50)
    
    if tweets is None:
        print('It is not possible to load timeline')
        sys.exit(1)
    
    tokenizer = nltk.tokenize.TweetTokenizer(preserve_case=False)
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        tokens = tokenizer.tokenize(tweet)
        positive_score = 0
        negative_score = 0
        for token in tokens:
            score = analyzer.analyze(token)
            if score > 0.0:
                positive_score +=1
            if score < 0.0:
                negative_score -=1
        score = positive_score+negative_score       
        
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))    
        
if __name__ == '__main__':
    main()
